# https://taskfile.dev

version: "3"

vars:
  DOTFILES_DIRECTORY: "./dotfiles"

tasks:
  default:
    desc: lists tasks
    cmds:
      - task --list-all
    silent: true
  setup-dotfiles:
    # In `dotfiles` directory run `stow -t ~ -v *` which means:
    # Stow to `~` verbose so that you can see what happens
    # `*` glob to everything in current directory
    desc: setup dotfiles
    dir: "{{.DOTFILES_DIRECTORY}}"
    cmds:
      - stow -t ~ -v *
