-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "catppuccin-mocha-pink-cursors")
hl.env("XCURSOR_THEME", "catppuccin-mocha-pink-cursors")
hl.env("HYPRCURSOR_SIZE", "32")
hl.env("XCURSOR_SIZE", "32")
