-- Auto-generated by DMS - do not edit manually

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 4,
        border_size = 2,
    },
    decoration = {
        rounding = 8,
    },
})

