-- Auto-generated by DMS - do not edit manually

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@60.000",
    position = "0x0",
    scale = "1",
    vrr = 0,
})

hl.monitor({
    output = "DP-2",
    mode = "2560x1080@59.978",
    position = "1920x0",
    scale = "1",
    vrr = 0,
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.000",
    position = "4480x853",
    scale = "1",
    vrr = 0,
})

