-- Auto-generated by DMS - do not edit manually

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "DP-2",
    mode = "2560x1080@74.991",
    position = "2193x4801",
    scale = "1",
    vrr = 0,
})

hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@60.000",
    position = "273x4801",
    scale = "1",
    vrr = 0,
})

hl.monitor({
    output = "desc:BNQ BenQ LCD L8N00698019",
    mode = "1920x1080@60.000",
    position = "320x0",
    scale = "1",
    vrr = 0,
})

hl.monitor({
    output = "desc:LG Display 0x0695",
    mode = "2560x1600@60.003",
    position = "0x1080",
    scale = "1",
    vrr = 0,
})
