-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "desc:Dell Inc. DELL P2414H KKMMW63SA6MM", mode = "1920x1080@60.000", position = "0x0", scale = 1, vrr = 0 })
hl.monitor({ output = "desc:LG Electronics LG HDR WFHD 0x000962FE", mode = "2560x1080@74.991", position = "1920x0", scale = 1, vrr = 1, bitdepth = 10 })
