--workspaces
--1
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "windowrule-1",
    match = {
        class = "^((F|f)irefox)$",
        title = "^(Mozilla Firefox)$",
    },
    workspace = "1",
})

--3
hl.window_rule({
    name = "windowrule-2",
    match = {
        class = "^((E|e)macs)$",
    },
    workspace = "3",
})

hl.window_rule({
    name = "windowrule-3",
    match = {
        class = "^(jetbrains-idea)$",
        title = "^(jetbrains-idea)$",
    },
    workspace = "3",
})

hl.window_rule({
    name = "windowrule-4",
    match = {
        class = "^(code-url-handler)$",
    },
    workspace = "3",
})

--4
hl.window_rule({
    name = "windowrule-5",
    match = {
        class = "^(org.pwmt.zathura)$",
    },
    workspace = "4",
})

hl.window_rule({
    name = "windowrule-6",
    match = {
        class = "^((N|n)sxiv)$",
    },
    workspace = "4",
    maximize = true,
    float = false,
})

--File management
hl.window_rule({
    name = "windowrule-7",
    match = {
        class = "^((T|t)hunar)$",
    },
    workspace = "5",
})

hl.window_rule({
    name = "windowrule-8",
    match = {
        class = "^((P|p)cmanfm)$",
        class = "^(org.gnome.Nautilus)$",
        class = "^(org\\.musicbrainz\\.Picard)$",
    },
    workspace = "5",
})

-- 7
hl.window_rule({
    name = "windowrule-11",
    match = {
        class = "^((org\\.jellyfin\\.jellyfinmediaplayer)|(Jellyfin Media Player)|(com.github.iwalton3.jellyfin-media-player))$",
        class = "^(steam)$",
    },
    workspace = "7",
})

hl.window_rule({
    name = "windowrule-13",
    match = {
        class = "^(discord|vesktop)$",
    },
    workspace = "6",
})

--GAMES
hl.window_rule({
    name = "windowrule-14",
    match = {
        class = "^(steam_app_)(.*)$",
        class = "^(cs2)$",
        title = "^(X4)$",
    },
    workspace = "8",
    fullscreen = true,
    immediate = true,
    no_anim = true,
    border_size = 0,
    rounding = false,
})

--video watching stuff
hl.window_rule({
    name = "windowrule-18",
    match = {
        class = "^(mpv)$",
    },
    workspace = "9",
})

