-- Generated by nwg-displays on 2025-12-10 at 18:00:07. Do not edit manually.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = "1.0",
})

hl.monitor({
    output = "DP-2",
    mode = "2560x1080@59.98",
    position = "1920x0",
    scale = "1.0",
    bitdepth = 10,
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "4480x441",
    scale = "1.0",
    transform = 0,
})

